spring.data.mongodb.uri=mongodb+srv://Samath:sam123@sam.2yckomn.mongodb.net/Pet-Adoption?retryWrites=true&w=majority

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
upload.dir=uploads
